clear;
clc;
fun = @(x) cosh(x).*(1 - x.^2);
x = -1:0.01:2;
figure('Name', 'Интегрирование', 'NumberTitle', 'off');
area(x, fun(x));
hold on;
grid on;
S = integral(fun, -1, 2, 'AbsTol', 0.0001);
fprintf('Результат численного интегрирования %f \n', S);