clear;
clc;
fun = @(x) sin(1./x).*x.^4;
xmin = 1;
xmax = 2.5;
x = 1:0.1:2.5;
a = trapz(x, fun(x));
b = integral(fun, xmin, xmax, 'AbsTol', 5e-4);
fprintf('Результат интегрирования трапециями: %f \n', a);
fprintf('Результат численного интегрирования: %f \n', b);
fprintf('Величина ошибки: %f \n', a - b);
figure('Name', 'Area', 'NumberTitle', 'off');
area(x, fun(x));
xlabel('X');
ylabel('Y');
legend('fun(x)');
grid on;