clear;
clc;
fun = @(x, y) log(1 + x.^2 + y.^2).^2 + (x - y - 1).^2 - 0.1164;
[X,Y] = meshgrid ([-10:0.1:10, -10:0.1:10]);
Z = fun(X, Y);
figure('Name', 'fminsearch', 'NumberTitle', 'off');
hold on;
grid on;
surf(X, Y, Z-Z);
surf(X, Y, Z);
view([-81 11]);
xlabel('X');
ylabel('Y');
zlabel('Z');
colormap('jet');
title('Минимум функции от двух переменных');
a = integral2(fun, -10, 10, -10, 10);
fprintf('Результат численного интегрирования: %f \n', a);