clc;
clear;
t = 0:0.01*pi:2*pi;
x = 3*cos(t);
y = 3*sin(t);
fun = @(t) 3*sin(t) * 3;
s = 2*pi*integral(fun, 0, pi);
figure('Name', 'Рисунок', 'NumberTitle', 'off');
plot(x, y);
axis equal;
axis([-4 4 -4 4]);
fprintf("Площадь фрагмента %f \n", s);